networks:
  sfta:
    name: sfta
    driver: bridge

services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sfta

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - sfta
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: database
    image: mysql:5.6
    volumes:
      - ./database/mysql-data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    env_file:
      - database/.env
    networks:
      - sfta

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - sfta
