networks:
  sfta:
    name: sfta
    driver: bridge

services:

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sfta

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:8000"
    networks:
      - sfta
    depends_on:
      - mysql

  mysql:
    container_name: database
    image: mysql:5.6
    ports:
      - "33060:3306"
    volumes:
      - ./database/mysql-data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_USER=sfta
      - MYSQL_PASSWORD=sfta
      - MYSQL_ROOT_PASSWORD=sfta
      - MYSQL_DATABASE=sfta
    networks:
      - sfta